### ISSUE TITLE
404/400 bad request Kick.com (KickStreaming) error/not useable (BRAVE BROWSER - CHROMIUM BROWSERS)

### ISSUE THREAD

**Issue by eitaniel** [extesy/hoverzoom#1156]
### Discussed in https://github.com/extesy/hoverzoom/discussions/1155

<div type='discussions-op-text'>

<sup>Originally posted by **eitaniel** May 31, 2023</sup>
https://community.brave.com/t/kick-com-400-bad-request-error-only-on-brave-browser-working-fine-on-firefox-and-vivaldi-browsers/488349

greetings

the link above is my query on the brave browser community site, about a problem i've been having with kick.com. 

basically, i get a 404/400 bad request error, meaning i can't use kick.com for longer than a few minutes before the site gets locked or doesn't load up anymore. 

according to someone on that brave community forum, they found that deactivating hoverzoom plus solved the problem for them. i've just recently tried their recommended 'fix' myself, deactivating HZ+ and found that kick.com suddenly started working finely again. 

are the devs of hz+ aware of this issue with kick.com, especially on chromium browsers, but in my case specifically with brave browser? I also posted this query on reddit, on brave's reddit. i found that 3 other users have found this same issue, so it's not just my pc experience. I'm not sure if those users also have hz+ extension downloaded/installed, but perhaps they also do. 

anyway, please advise if hz+ would consider investigating why kick.com and hz+ don't seem to behave well together? 

thanks</div>

**Comment by eitaniel** [comment]
Many thanks

Really appreciate the quick reply!

**Comment by GrosPoulet** [comment]
@eitaniel this issue is fixed by #1159, you'll have to wait for next release of HZ+ (1.0.207)

**Comment by eitaniel** [comment]
highly appreciated! looking forward to the new version.

**Comment by eitaniel** [comment]
greetings

i'm writing to confirm that the fixes you stated you'd perform for hz+ on kick.com seem to not have been implemented. I am still getting 404 bad request error page upon activating hz+ and attempting to surf kick.com. it's almost instant fail. 

did you implement the fixes you suggested would be done according to this issues thread? I've had the addon deactivated as recommended since early June, with the hope of it being fixed as stated in this thread with the next version update (1.0.207), so it's confusing why this seems not to be the case.
