### ISSUE TITLE
Doesn't load all images on Reddit homepage

### ISSUE THREAD

**Issue by Atulin** [extesy/hoverzoom#1311]
**Describe the bug**

Only the first image is shown, the rest (after forcibly loading them due to #1209) show up as "probably deleted". Issue does not happen when the post itself is opened, only when the images are viewed on the homepage feed.

**To Reproduce**

1. Go to Reddit homepage
2. Find a post with multiple photos
3. Try to scroll through them

**Expected behavior**

All images are shown

**Screenshots**

https://github.com/extesy/hoverzoom/assets/11233299/e165d899-4195-4c3d-8b45-bdcd003f29c2

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser Firefox
 - Version 123.0b9 (64-bit)

**Comment by Atulin** [comment]
Update: sometimes *no images* are shown, at all.

https://github.com/extesy/hoverzoom/assets/11233299/03f30cc9-cf3c-4ec4-8b9b-9e86af802e04

**Comment by Atulin** [comment]
Seems the issue is because Hoverzoom is trying to load `.pn` files instead of `.png`
![image](https://github.com/extesy/hoverzoom/assets/11233299/fd5f1128-1c83-415f-8792-002cad43a6cf)

**Comment by extesy** [comment]
@Atulin I've tried https://www.reddit.com/r/xbox/comments/1aoenb5/lotr_gollum_console/ and it works just fine for me. Please provide specific links instead of just a generic "reddit homepage" which is different for everybody.

**Comment by Atulin** [comment]
As I said, it works perfectly fine when you enter any particular post like in your example. It does not work on the homepage.

If the term "homepage" is unclear then I'm sorry, here's the direct link: https://reddit.com

**Comment by extesy** [comment]
I know how to find the reddit homepage :)
What I meant if that when that particular post was on my homepage I was able to scroll through all its gallery images. Perhaps it is related to the "new reddit" design which I do not use, so I'll need to check that.

**Comment by Atulin** [comment]
Yes, it is the new design. Here's an [example post](https://www.reddit.com/r/arknights/comments/1api440/house_of_the_dragons_but_asian_by_%E5%B7%A6%E5%88%80%E8%A1%8C/)

**Comment by Atulin** [comment]
Update: Reddit got *another redesign* and now HoverZoom doesn't work at all. Not on the homepage, not in the post view.

https://github.com/extesy/hoverzoom/assets/11233299/36d30a52-0531-4c7f-bb19-476a74c436ce

Post: https://www.reddit.com/r/NameNerdCirclejerk/comments/1aqq6h8/list_of_banned_names_in_italy/

**Comment by extesy** [comment]
This only applies to galleries. Individual images are still zooming successfully.

**Comment by extesy** [comment]
Should be fixed by aac830bdafd95466df88c9b8a9f1bf2c915a01b3, I'll release a hotfix soon.

**Comment by max1c** [comment]
> Should be fixed by [aac830b](https://github.com/extesy/hoverzoom/commit/aac830bdafd95466df88c9b8a9f1bf2c915a01b3), I'll release a hotfix soon.

I hate posting in a resolved issue but I'm still seeing this bug: 
![image](https://github.com/extesy/hoverzoom/assets/11587156/1f97a639-f999-4f4a-858c-60572a38abb2)

It only happens on the main page before you open the actual post.
