### ISSUE TITLE
Redgif not loading

### ISSUE THREAD

**Issue by TipuSultan14** [extesy/hoverzoom#1412]
**Describe the bug**
Redgif used to run as normal, since the last update it has stopped to load.

**To Reproduce**

**Expected behavior**
Redgif links should zoom on hover

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Edge
 - Version:  128.0.2739.67 

**Additional context**

**Comment by extesy** [comment]
Fixed in https://github.com/extesy/hoverzoom/commit/8998271055bae2d79873a7d504965eb6c314e147

**Comment by dbasinge** [comment]
Have the updated to version 1.0.220 (dated Sept 9 ,2024) and still seeing the issue

**Comment by extesy** [comment]
@dbasinge Open a new issue with detailed repro steps. Everything seems to work for me.
