### ISSUE TITLE
Redgifs and v3.redgifs no longer loads videos or picture

### ISSUE THREAD

**Issue by rlyehfhtagn** [extesy/hoverzoom#1417]
**Describe the bug**
When hovering over links for redgifs.com or v3.redgifs.com on reddit (I assume other places too), the image or video does not appear. The little loading spinner does pop up, but not the actual content.

**To Reproduce**
1. Go to any NSFW subreddit that has videos, like /r/bigtitsinbikinis
2. hover over link to redgifs.com or v3.redgifs.com
3. see loading animation, but the content will not load 

**Expected behavior**
A video or picture pops up, the video should auto play with audio if it has audio

**Screenshots**
![image](https://github.com/user-attachments/assets/02f24157-4c7a-40b5-913c-4e2a709c9030)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit
 - Browser: Edge
 - Version 128.0.2739.79

**Additional context**

**Comment by extesy** [comment]
@rylehfhtagn What is the extension version? This was fixed in `1.0.220`.

**Comment by rylehfhtagn** [comment]
> @rylehfhtagn What is the extension version? This was fixed in `1.0.220`.

That is the version I have. I had tried uninstalling and reinstalling the extension, and I verified that the redgifs addons are enabled.

**Comment by Kreshniku** [comment]
Same issue, I've been having this for more than a couple weeks. Tried Edge, Chrome, Brave, with existing or new profiles, enabling and disabling adblockers and all other extensions. Issue persists.

**Comment by zekecounter** [comment]
no luck on my end aswell, desktop edge Version 128.0.2739.79 (Official build) (64-bit)

**Comment by extesy** [comment]
@yadue Any clues?

**Comment by extesy** [comment]
Do you all have this option turned on?
![image](https://github.com/user-attachments/assets/a28b4fac-a425-4d73-9892-e60394b0bacd)

**Comment by Jd-19** [comment]
> Do you all have this option turned on? 

Turning this option on has just fixed the issue for me

**Comment by extesy** [comment]
All right, mystery solved.

**Comment by Lumi-sg** [comment]
> Do you all have this option turned on? ![image](https://private-user-images.githubusercontent.com/65872/367945165-a28b4fac-a425-4d73-9892-e60394b0bacd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjU1OTcsIm5iZiI6MTcyNjc2NTI5NywicGF0aCI6Ii82NTg3Mi8zNjc5NDUxNjUtYTI4YjRmYWMtYTQyNS00ZDczLTk4OTItZTYwMzk0YjBiYWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE3MDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZjQ3YjRjODc2YzJjYmU3NDk4MWFkYTg4OTA3ZjQ4ODg5NjkxOGM1Y2YzYzdmYjFhMDNhM2QwMTEzMzRjZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pChZ1Aqslkte01LjCGF38_H0ad-9ryprniEybGgJUrE)

This worked for me on Edge but not Firefox
