### ISSUE TITLE
Stopped working on rule34

### ISSUE THREAD

**Issue by Abbaddon911** [extesy/hoverzoom#1482]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
On rule34.xxx, hoverzoom tries to load any image, no matter if it's .gif .jpeg .jpg or .png, as mp4 for what ever reason.
Happens since 2 or 3 days.
Video never worked for me. Hoverzoom would zoom them but not play them.

Console shows this as "error":
"[HoverZoom] Failed to load source: <link_to_image>.mp4
Trying again with custom headers..."
And the file reported is "hoverzoom.js:1861"

## Url of the page where the problem occurs (not the image url)
Whole site affected

## Steps to reproduce the problem (include image url here)
1. Look for any image
2. Hover over any image
3. Spinner shows up and console shows mentioned error message

## OS version, extension version
Win11 23H2 (Build 22631.4541) (can't update to 24H2 due to ASUS having issues with that...again...)
Hoverzoom is 1.0.222 on Chrome and Firefox (both affected)

(Edited the mistyped URL to the correct on)

**Comment by LiliaDoe** [comment]
If you update hz+ to 1.0.223, it should be fixed. I tested it on chrome and firefox on the latest version, and it worked

**Comment by extesy** [comment]
@Abbaddon911 I'm closing this report as fixed. Feel free to follow up if it doesn't work for you in 1.0.223.

**Comment by Abbaddon911** [comment]
Updated to 1.0.223 on both Chrome and Firefox, and just to sanity check myself I also did a clean Firefox install on my Laptop which didn't have Firefox.

The issue persists on both, HZ+ still tries to load images as MP4 files on rule34.xxx. (I just saw, I mistakenly wrote "rule34.net" in my OP)
Maybe that's the issue? The URL? I know there is also the paheal.net one where it works as it should, but also has vastly different images.

The file reported in the console is the same "hoverzoom.js", but the line number changed to "2049" and "2075", the message is still the same.

**Comment by extesy** [comment]
@LiliaDoe I've just tried this site myself and it the images are not zooming for me, so I'm reopening the issue.

**Comment by LiliaDoe** [comment]
oh, i was on the wrong rule34 url when testing too

**Comment by Abbaddon911** [comment]
Sorry to bother you again, and this might be an issue on my end now, but it's still broken for me.

Version is still 1.0.223

I checked the file that was changed for the fix in my extensions folder and noticed that it's still the unfixed one.
Replacing that with the fixed one, chrome disables the extension, reports it as broken and asks me if I want to repair it, which leads to chrome uninstalling and reinstalling the extension.
If I decline to repair it, it just stays disabled.

Any help on this one, please?

**Comment by LiliaDoe** [comment]
The 1.0.224 just released. it should be fixed now
