### ISSUE TITLE
Not adding links to history.

### ISSUE THREAD

**Issue by dudeman9000** [extesy/hoverzoom#278]
## Firefox?
CHROME

## Description of the problem
Links no longer added to history.

## Url of the page where the problem occurs (not the image url)
All sites I have checked; Reddit, Facebook, Youtube, etc...

## Steps to reproduce the problem (include image url here)
1. Install Hover Zoom + on Chrome.
2. Change settings to add links to history and authorize extension to do so.
3. ???
4. Sell as lakefront property.
5. See that links are not added to history.

## OS version, extension version
Chrome version 60.0.3112.78 (Official Build) (64-bit)
Windows 10 Pro (cant find version or build number anywhere, its still a new OS to me)
Hover Zoom + version 1.0.118

**Comment by extesy** [comment]
Hm... Probably some recent change in the Chrome API behavior.

**Comment by dudeman9000** [comment]
Is that something I can change myself? Or would I have to wait for an update to Hover Zoom +?

**Comment by extesy** [comment]
You'll have to wait.

**Comment by hatterson** [comment]
I'm receiving the same issue on chrome 59.0.3071.  With the console open I see the following error when hovering over an image:

Uncaught TypeError: Cannot read property 'href' of undefined
    at displayFullSizeImage (hoverzoom.js:635)
    at HTMLImageElement.imgFullSizeOnLoad (hoverzoom.js:531)
    at HTMLImageElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLImageElement.q.handle (jquery-3.2.1.min.js:3)

Which links to this line of code:
                var url = hz.currentLink.context.href || imgDetails.url;

Occasionally it'll also throw a similar error referencing the same line of code just on a different call stack:

Uncaught TypeError: Cannot read property 'href' of undefined
    at displayFullSizeImage (hoverzoom.js:635)
    at posWhileLoading (hoverzoom.js:285)
    at loadFullSizeImage (hoverzoom.js:488)

When I updated to 60.0.3112 I receive the same two errors

**Comment by extesy** [comment]
Fixed in `1.0.120`

**Comment by ahoibakk** [comment]
@extesy I'm still facing this issue. I have tried disable and the reenable the setting. It looks like the URL is added to my history, but it's not showing up as viewed, even after a reload.

I have updated to 1.0.120 (issue #281 is fixed).

Video here: https://img.m42.no/7f7ad618-f365-4903-bedd-b67c3ad2b768.mp4

**Comment by dudeman9000** [comment]
As am I. However, it seems to work for few random links. I haven't seen any pattern to which links it adds to history though, almost entirely random it seems.
