### ISSUE TITLE
Saving image keyboard shortcut is not saving image, instead loads the image in same tab

### ISSUE THREAD

**Issue by Sushubh** [extesy/hoverzoom#344]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Pressing S when image is hovering used to save image as configured in settings. But in recent builds, instead of saving the image, the image loads in the same tab as the web page. 

## Url of the page where the problem occurs (not the image url)
Has been happening all around. Twitter, Google Image Search. Even regular websites like https://www.pexels.com/search/HD%20wallpaper/ 

## Steps to reproduce the problem (include image url here)
1. Load a website where hoverzoom would work like https://www.pexels.com/search/HD%20wallpaper/
2. Hover cursor over an image to let the extension do its magic. 
3. Press the S key to try to save it on local machine. 

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10
1.0.125

**Comment by 07416** [comment]
> Pressing S when image is hovering used to save image as configured in settings. But in recent builds, instead of saving the image, the image loads in the same tab as the web page.

Applies to Firefox as well (Firefox appears to be supported now):

Windows 10
Hover Zoom+ 1.0.127
Firefox 58.0.2

**Comment by extesy** [comment]
Firefox is not supported. Just because people open issues for Firefox doesn't mean I support that extension.

**Comment by k1ngisamu** [comment]
Same issue started to happen after upgrading chrome to 65.0.3325.146 version (official build).
After pressing S to save image, image just loads on same tab.

**Comment by oraclist** [comment]
For me this happened with update Chrome 64bit to Version 65 on Windows7. Chrome 65 on Ubuntu 17.10 works still as it should.

**Comment by CaptnFabulous** [comment]
Happening to me too, for at least the past few weeks. Chrome 64/65 x64 Win10.

**Comment by grady514** [comment]
Yup, having the same problem in Chrome Win 10.  It started a few days ago.

**Comment by zyotl** [comment]
Im having the same problem, actually this feature is what makes me use chrome, instead of firefox which i would like, please fix this, i want to save photo only pressing "S" instead of opening and then ctrl+s, thank you

**Comment by yadue** [comment]
It's related to limitations in chrome 65, see:
https://www.chromestatus.com/feature/4969697975992320

**Comment by eaxexe** [comment]
Experiencing this too.

**Comment by albertoglezba** [comment]
Me too on Debian buster, Versión 65.0.3325.146 (Build oficial) (64 bits)

**Comment by UDEFO** [comment]
Same issue, pressing S doesn't work anymore

**Comment by ramza2** [comment]
Same issue;
press 'S' ->  image loads in the same tab -> hover againt and press 'S' -> then works

**Comment by ivan2340** [comment]
I have put up a fix for it, should be working as soon as it get's merged, however downloadpath get's reset everytime, don't think there's a way around that

**Comment by Litvinr** [comment]
Save action keys still not working after update hoverzoom to Version 5.26.9 
I wont switch to Imgaus because love HoverZoom , but if bug not will fixed asap i don't having another choise

Windows7 x64
Chromium Version 65.0.3400.0 (Official Build) (64-bit)

**Comment by desperte** [comment]
@ivan2340 when will it be merged and how can I update to that version thanks

**Comment by extesy** [comment]
@desperte available now in 1.0.75

**Comment by mahendranv** [comment]
Anyone else can confirm whether **Save** not working?

I am on Chrome Version 70.0.3538.77 (Official Build) (64-bit)
Hover zoom: V 6.0.3

**Comment by ddpatel4241** [comment]
Same issue. occurring since last some times. using latest chrome and latest extension.  
Saving image keyboard shortcut is not saving image, instead loads the image in same tab
