### ISSUE TITLE
instagram links appear to fetch images over insecure connection

### ISSUE THREAD

**Issue by Sushubh** [extesy/hoverzoom#372]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Instagram links appear to be loading images on HTTP resulting in full screen chrome app (like tweetdeck) making address bar visible or resulting in mixed content error on secure webpages. 

## Url of the page where the problem occurs (not the image url)
https://app.simplenote.com/p/4DFmc0

## Steps to reproduce the problem (include image url here)
1. Find a secure (https) web page with an instagram link on it. 
2. Try to load that image by hovering over link. 
3. https page ends up showing mixed content warning. browser console show that instagram was fetched over http. 
PS: This is kind of becoming an issue on TweetDeck for me. I run it in a full screen web app format using Chrome. And whenever I hover on an Instagram link, the web app ends up loading the address bar inside it because that's how Chrome deals with loading of insecure elements or change of domain. I use another Chrome extension to convert t.co links to actual links on TweetDeck enabling me to use this extension there. 

## OS version, extension version (Chrome only, Firefox is not supported)
latest chrome stable and extension build.

**Comment by lapo-luchini** [comment]
Provided link seems to open an https hover already, I guess it was already fixed in the meantime?

**Comment by extesy** [comment]
I guess so. I think 9e41c8651cd061153613b84557475ce02b40c532 fixed it.

**Comment by Sushubh** [comment]
I am not sure why it is still not fixed for me! 

https://imgur.com/a/Hx30AMO

**Comment by lapo-luchini** [comment]
Right, starts on HTTPS end un on HTTPS but the first 301 redirect is on HTTP. Curious.
![image](https://user-images.githubusercontent.com/420454/41837755-bef15f16-785e-11e8-8814-65f72823bee2.png)

**Comment by ivan2340** [comment]
@extesy fixed

**Comment by ivan2340** [comment]
@extesy close?
