### ISSUE TITLE
Spinner for loading video comes up and stays when Zoom Videos is unselected

### ISSUE THREAD

**Issue by JeffAtPropeller** [extesy/hoverzoom#75]
I unselected "Zoom Videos" in the options but if my cursor goes over a video link it will pop up a loading /progress spinner that never goes away.

If I select "Zoom Videos" I don't see it on the screen.

**Comment by jonluca** [comment]
What are your other options? I can't seem to reproduce this.

What video links are you attemping? I am simply trying a link on reddit.com/r/videos, is there a specific site this happens with?

**Comment by jonluca** [comment]
Anyways I just made a pull request that I *believe* should fix it, as it calls `cancelImageLoading();` before returning.

**Comment by extesy** [comment]
@JeffAtPropeller please try the latest version (1.0.73) and confirm if the issue is fixed.

**Comment by extesy** [comment]
Based on the users reports, this looks like it's still happening.
